javax.persistence.jdbc.driver=com.mysql.jdbc.Driver
javax.persistence.jdbc:postgresql://localhost:5432/inventario
javax.persistence.jdbc.user=root
javax.persistence.jdbc.password=$uP3rn0V@
hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update