
# ===============================
# POSTGRESQL CORRETO
# ===============================
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/inventario
hibernate.connection.username=root
hibernate.connection.password=$uP3rn0V@

# ===============================
# DIALECT
# ===============================
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# DEBUG
# ===============================
hibernate.show_sql=true
hibernate.format_sql=true

# ===============================
# AUTO TABELA
# ===============================
hibernate.hbm2ddl.auto=update
